# Generated by Django 5.0.6 on 2024-07-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_alter_favorite_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
