# Generated by Django 5.0.6 on 2024-10-12 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_alter_album_audiodb_idalbum_and_more'),
        ('favorites', '0004_alter_favorite_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred', to='albums.album'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('owner', 'album')},
        ),
    ]
