# Generated by Django 5.0.6 on 2024-10-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0005_alter_favorite_album_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
