# Generated by Django 5.0.6 on 2024-10-12 17:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_alter_album_audiodb_idalbum_and_more'),
        ('favorites', '0006_alter_favorite_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('owner', 'album')},
        ),
    ]
