# Generated by Django 5.0.6 on 2024-07-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['release_year']},
        ),
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.AddField(
            model_name='album',
            name='album_format',
            field=models.CharField(default='Album', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='audiodb_idAlbum',
            field=models.SmallIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='audiodb_idArtist',
            field=models.SmallIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(default='This album...'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='discogs_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.CharField(default='Label', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.SmallIntegerField(default=1970),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='style',
            field=models.CharField(default='Rock', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='wikipedia_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(default='Rock', max_length=255),
            preserve_default=False,
        ),
    ]
