# Generated by Django 5.0.6 on 2024-07-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_alter_album_album_format_alter_album_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
