# Generated by Django 5.0.6 on 2024-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_alter_album_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='audiodb_idAlbum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='audiodb_idArtist',
            field=models.IntegerField(),
        ),
    ]
