# Generated by Django 5.0.6 on 2024-11-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_alter_album_audiodb_idalbum_and_more'),
        ('reviews', '0003_alter_review_album_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='albums.album'),
        ),
    ]
